version: '2'

services:
  nzbget:
    build: .
    image: cturra/nzbget:latest
    container_name: nzbget
    restart: always
    environment:
      - NZBGET_TRACK=stable
    ports:
      - 6789:6789
    volumes:
      - /data/nzbget:/data
      - /data/downloads:/data/downloads
